export const UPDATE_TASK_NAME = 'UPDATE_TASK_NAME';
export const ADD_NEW_TASK = 'ADD_NEW_TASK';
export const SET_NOTEBOOKS = 'ADD_NOTEBOOKS'
export const SET_SECTIONS = 'LOAD_SECTIONS';
export const SELECT_NOTEBOOK = 'SELECT_NOTEBOOK';
export const LOAD_SECTIONS = 'LOAD_SECTIONS'
export const SELECT_SECTION = 'SELECT_SECTION';
export const SET_LOADING_SECTIONS = 'SET_LOADING_SECTIONS';